# Generated by Django 5.0.7 on 2024-08-04 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("measurements", "0001_initial"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="measurements",
                related_query_name="measurement",
                to="stations.station",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="measurement",
            unique_together={("station", "date_captured")},
        ),
    ]
